### ISSUE TITLE
rake error.

### ISSUE THREAD

**Issue by momobalon** [anvyzhang/deploli#1]
after running  "ruby deploli.rb"

/usr/lib/ruby/gems/1.8/gems/rack-1.6.4/lib/rack/handler.rb:22:in `const_get': wrong number of arguments (2 for 1) (ArgumentError)
        from /usr/lib/ruby/gems/1.8/gems/rack-1.6.4/lib/rack/handler.rb:22:in`get'
        from /usr/lib/ruby/gems/1.8/gems/sinatra-1.4.6/lib/sinatra/base.rb:1777:in `detect_rack_handler'
        from /usr/lib/ruby/gems/1.8/gems/sinatra-1.4.6/lib/sinatra/base.rb:1775:in`each'
        from /usr/lib/ruby/gems/1.8/gems/sinatra-1.4.6/lib/sinatra/base.rb:1775:in `detect_rack_handler'
        from /usr/lib/ruby/gems/1.8/gems/sinatra-1.4.6/lib/sinatra/base.rb:1437:in`run!'
        from /usr/lib/ruby/gems/1.8/gems/sinatra-1.4.6/lib/sinatra/main.rb:25

**Comment by anvyzhang** [comment]
Better use ruby 1.9 or above
